linters:
  enable-all: true
  enable:
      - deadcode
      - depguard
      - errcheck
      - goconst
      - gocritic
      - gocyclo
      - gofmt
      - goimports
      - golint
      - gosimple
      - govet
      - ineffassign
      - megacheck
      - misspell
      - structcheck
      - typecheck
      - unconvert
      - varcheck

linters-settings:
  depguard:
    list-type: whitelist
    packages:
      -	github.com/360EntSecGroup-Skylar/excelize
      - github.com/bogem/id3v2
      - github.com/eduncan911/podcast
      - github.com/gocarina/gocsv
      - github.com/sirupsen/logrus
      - gopkg.in/yaml.v2
      - github.com/pkg/errors
      - github.com/rasa/feedster/podcast
      - github.com/rasa/feedster/version   

issues:
  exclude-use-default: false
  exclude:
    # errcheck: Almost all programs ignore errors on these functions and in most cases it's ok
    - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
    
